[package]
name = "mekena-state"
description = "State storing utilities for the Mekena scheduling system."
version = "0.1.0"

license = "MIT"
repository = "https://github.com/bobbbay/mekena"

edition = "2021"
rust-version = "1.62"

[dependencies]
dashmap = "5.4.0"
