name: MSRV

on: [push, pull_request]

jobs:
 check:
   name: Check
   runs-on: ubuntu-latest
   strategy:
     matrix:
       rust:
         - nightly
   steps:
     - name: Checkout sources
       uses: actions/checkout@v3

     - name: Install toolchain
       uses: actions-rs/toolchain@v1
       with:
         toolchain: ${{ matrix.rust }}
         override: true

     - name: Run cargo check
       uses: actions-rs/cargo@v1
       with:
         command: check

test:
  name: Test Suite
  runs-on: ubuntu-latest
  strategy:
    matrix:
      rust:
        - nightly
  steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
